### ISSUE TITLE
Update to 20160205

### ISSUE THREAD

**Issue by mattleibow** [userzimmermann/choco-packages#1]
Nice package, and chance of an update to the "msys2-x86_64-20160205.exe" version?

**Comment by userzimmermann** [comment]
Hi @mattleibow 
Thanks! And yes. The update is one of my next tasks, besides some dependent packages...
And sorry for the late reply :)

**Comment by dragon788** [comment]
Hopefully this will get updated soonish. Was just looking and their latest is much newer, and they have a single click installer, though it probably doesn't use the same paths as your custom script.

**Comment by petemounce** [comment]
@mattleibow @userzimmermann @dragon788 I've just opened #4 to fix this.

**Comment by userzimmermann** [comment]
Thanks to @petemounce and #3 and #4 the install script is now updated to MSY2 20160716
I will reorder things a bit into my branch structure and then upload the new package.
@mattleibow @dragon788 @rgl @koppor Sorry for the long waiting time :)
