### ISSUE TITLE
do not show which files are being extracted

### ISSUE THREAD

**Issue by rgl** [userzimmermann/choco-packages#2]
I'm installing msys inside a vagrant environment, but showing the extracted files is making things hard for me, as it "pollutes" the output and makes it hard to find any errors on the output. can you omit the extracted file names from the output? I'm talking about these lines:

```
Extracting  msys64\var\lib\pacman\local\libtasn1-4.7-1\install
Extracting  msys64\var\lib\pacman\local\libtasn1-4.7-1\mtree
Extracting  msys64\var\lib\pacman\local\libutil-linux-2.26.2-1
```

**Comment by rgl** [comment]
Oh, this is really an issue with chocolatey. They are not passing the `-bd` argument to 7z. I'll open the issue with them.

**Comment by rgl** [comment]
I've moved this to the [choco repo](https://github.com/chocolatey/choco/issues/693). Sorry for the noise.

**Comment by userzimmermann** [comment]
@rgl np! nice that you are using my package :)
