### ISSUE TITLE
Update MSYS2 to 20160921

### ISSUE THREAD

**Issue by userzimmermann** [userzimmermann/choco-packages#5]
After missing to updade to 20160205 as requested in #1 and pulling #4  which updates to 20160719, I saw that there is an even newer 20160921 release. I will better use that for the next Chocolatey MSYS2 package release.

**Comment by userzimmermann** [comment]
Done with https://github.com/userzimmermann/choco-packages/commit/acab860aa9085a3bebeb26db4aeeb4cc10a82d95

**Comment by petemounce** [comment]
Cool! I'd very much like a new version to be published, since the 2015 one currently available fails to install and so blocks https://chocolatey.org/packages/bazel/0.3.2 from passing automated validation, since msys2 is a dependency.
